lms/urls.py
from lms.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path , include
# ***** to setup static media *******
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('lms_app.urls'))
]

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT) 

lms_app/urls.py
from django.urls import path
from . import views
app_name='lms_app'

urlpatterns = [
    path('', views.index , name='index'),
    path('books', views.books , name='books'),
    path('update/<int:id>', views.update , name='update'),
    path('delete/<int:id>', views.delete , name='delete'),
]

templates/pages/books.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div style="direction: rtl;" class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper p-5">
      <!-- Content Header (Page header) -->

              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>الكتب</h1>
                </div>
 
              </div>
          </section>
      
          <!-- Main content -->
          <section class="content">                  
            <!-- Default box -->
            <div class="card card-solid">
              <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                  {% for book in books %}
                      <!-- بداية الكتاب -->
                      <div   class="col-12 col-sm-6 col-md-4 bookhide book{{book.genre.first.id}} book{{book.status}} ">
                        <div  id="" class="card bg-light">
                          {% for gn in book.genre.all|slice:'1' %}
                          <div  class="card-header text-muted border-bottom-0">
                            {{gn}}
                          </div>
                          {% endfor %}
                          <div class="card-body pt-0">
                            <div class="row">
                              <div class="col-7">
                                <h2 class="lead"><b>{{book.title}}</b></h2>
                                <ul class="  fa-ul text-muted">
                                  <li class="small"><span class="fa-li"></span> الحالــة : {{book.status}}  </li>
                                  {% if book.price %}
                                      <li class="small"><span class="fa-li"></span> السعر: ${{book.price}}</li>
                                  {% elif book.rental_price_day %}
                                      <li class="small"><span class="fa-li"></span> فى اليــوم: ${{book.rental_price_day}}</li>
                                  {% endif %}
                                </ul>
                              </div>
                              <div class="col-5 text-center">
                                {% if book.book_img %}
                                     <img style="height: 120px; width: 120px;"  src="{{book.book_img.url}}" alt="" class="img-circle img-fluid">
                                {% else %}
                                     <img style="height: 120px; width: 120px;"  src="{% static 'dist/img/photo1.png' %}" alt="" class="img-circle img-fluid">

                                {% endif %}
                                  
                                </div>
                            </div>
                          </div>
                          <div class="card-footer">
                            <div class="text-right">
                              <a href="{% url 'lms_app:delete' book.id %}" class="btn btn-sm bg-danger">
                                <i class="fas fa-trash"></i>
                              </a>
                              <a href="{% url 'lms_app:update' book.id %}" class="btn btn-sm btn-primary">
                                <i class="fas fa-book"></i> تعديل
                              </a>
                            </div>
                          </div>
                        </div>
                        
                      </div>
                      <!-- نهاية الكتاب -->
                  {% endfor %}
                 
                 
                 
                  
                </div>
              </div>
              <!-- /.card-body -->

              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
      
          </section>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      
    </div>
    <!-- /.content-wrapper -->
  </div>


{% endblock content %}

templates/pages/delete.html
{% extends 'base.html' %}



{% block content %}

<div style="direction: rtl;" class="wrapper">

    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper">
      <!-- Content Header (Page header) -->
  <div  class="card card-danger">
      <div class="card-header">
        <h3 class="card-title">حذف الكتاب</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form  method="POST" enctype="multipart/form-data">
      {% csrf_token  %}
      
        <div class="row">
          
       <p class="p-3">هل تريد حقاً حذف الكتاب؟</p>
   
        </div>
        <!-- /.card-body -->
  
        <div class="card-footer">
          <button type="submit" class="btn btn-danger">حذف</button>
  
          <a href="{% url 'lms_app:index' %}" type="submit" class="btn btn-secondary">تراجع</a>
        </div>
      </form>
    </div>
  </div>
  </div>
    


{% endblock content %}















  

templates/pages/index.html
{% extends 'base.html'%}
  
  
  {% block content %}


        <div style="direction: rtl;" class="wrapper">
          <!-- Content Wrapper. Contains page content -->
          <div   class="content-wrapper">
            <!-- Content Header (Page header) -->
<!-- ********************************* HIDEN CODE ***************** -->
            {% for book in books %}
                {% if book.price != None and book.status == 'sold' %}
                  <h1 class="totalPrice" > {{book.price}}</h1> 
                {% endif %}

                {% if book.total_rental != None and book.status == 'rental' %}
                  <h1 class="totalPrice"> {{book.total_rental}} </h1>            
              
               {% endif %}

            {% endfor %}

        <!-- rental books -->
        {% for book in books %}
            {%if book.total_rental != None and book.status == 'rental' %}
                <h1 class="totalRental">{{book.total_rental}}</h1>
            {% endif %}
            
      {% endfor %}
            <p class="salaryRental"></p>

        <!-- Sold books -->
     {% for book in books %}
        {%if book.price != None and book.status == 'sold' %}
           <h1 class="totalPrice">{{book.price}}</h1>
        {% endif %}
    {% endfor %}
        <p class="salaryPrice"></p>



<!-- ********************************* HIDEN CODE ***************** -->



            <!--الاحصائيات-->
            <div class="content">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="card">
                      <div class="card-header border-0">
                        <div class="d-flex justify-content-between">
                          <h3 class="card-title">اجمالي عدد الكتب</h3>
                        </div>
                      </div>
                      <div class="card-body">
                        <div class="d-flex">
                          <p class="d-flex flex-column">
                            <span class="text-bold text-lg">{{all_books}}</span>
                            <span>اجمالي عدد الكتب</span>
                          </p>
                        </div>
                        <!-- /.d-flex -->

                        <div class="position-relative mb-4">
                          <canvas id="visitors-chart" height="200"></canvas>
                        </div>
                      </div>
                    </div>
                    <!-- /.card -->
                  </div>
                  <!-- /.col-md-6 -->

                  <div class="col-lg-6">
                    <div class="card">
                      <div class="card-header border-0">
                        <div class="d-flex justify-content-between">
                          <h3 class="card-title">الارباح</h3>
                        </div>
                      </div>
                      <div class="card-body">
                        <div class="d-flex">
                          <p class="d-flex flex-column">
                            <span id="totalsalarys" class="text-bold text-lg">$</span><br></p>
                        </div>
                        <!-- /.d-flex -->

                        <div class="position-relative mb-4">
                          <canvas id="sales-chart" height="160"></canvas>
                        </div>

                        <div class="d-flex flex-row justify-content-end">
                          <span class="mr-2">
                            <i class="fas fa-square text-primary"></i> الاربح من بيع الكتب
                            <p id="soldtotals"></p>
                          </span>
                          <span>
                            <i class="fas fa-square text-gray"></i> الارباح من استعارة الكتب
                            <p id="rentedtotals"></p>
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <!-- /.col-md-6 -->
                </div>
                <!-- /.row -->

                {% if messages %}
                    {% for msg in messages%}
                      <div class="alert alert-{{msg.tags}}">
                        {{msg}}
                      </div>
                    {% endfor %}
                {% endif %}
                <!-- form add books -->
                <div class="row m-1 mb-3">
                  <a href="#bookform" class="btn btn-primary" data-toggle="collapse">+ اضافة كتاب</a>
                </div>

                <div id="bookform" class="card card-primary collapse">
                  <div class="card-header">
                    <h3 class="card-title">اضافة كتاب</h3>
                  </div>
                  <!-- /.card-header -->
                  <!-- form start -->
                  <form method="POST" enctype="multipart/form-data"  >
                    {% csrf_token %}
                    <div class="card-body">
                     {{form.as_p}}
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                      <button type="submit" class="btn btn-primary">اضافة</button>
                    </div>
                  </form>
                </div>

                      <!-- /.card -->
                </div>
                <!-- end form add books -->


                <!-- تصنيفات-->

                <div class="row justify-content-center mb-3">
                  <div class="col-4 ">
                    <ul class="nav">
                    {% for genre in genres|slice:'4' %}
                      <li class="nav-item genre{{genre.id}}">
                        <a id="" class="nav-link bg-primary" href="#">{{genre.name}}</a>
                    {% endfor %}
                    </ul>
                  </div>
                </div>
                <!-- ******* -->
                 <!-- Languages -->
                 <!-- <div class="row justify-content-center mb-3">
                  <div class="col-4 ">
                    <ul class="nav">
                    {% for language in languages|slice:'4' %}
                      <li class="nav-item language{{language.id}}">
                        <a id="" class="nav-link bg-primary" href="#">{{language.name}}</a>
                    {% endfor %}
                    </ul>
                  </div>
                </div> -->
                <!-- /end languages  -->

                <!-- books -->

                <div class="row">
                 {% for book in books %} 
                <!-- الكتب -->
                    <div id="" class="col-md-4 bookhide book{{book.genre.first.id}} book{{book.status}}">
                        <!-- Widget: user widget style 1 -->
                      <div id="" class="card card-widget widget-user ">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                      <!-- قائمة منسدلة -->
                      <div style="position: absolute;" class="btn-group">
                        <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'lms_app:update' book.id %}">تعديل</a>
                          <a class="dropdown-item" href="{% url 'lms_app:delete' book.id %}">حذف</a>
                      <!-- Button trigger modal -->
                        </div>
                      </div>
                    {% if book.book_img %}
                      <div class="widget-user-header bg-info" style="background: url({{book.book_img.url}});background-size: cover;">
                    {% else %}                   
                      <div class="widget-user-header bg-info"> 
                      {% endif %}
                        <h3 class="widget-user-username"> {{book.title}}</h3>
                        <h5 class="widget-user-desc">{{book.author}}</h5>
                      </div>
                      <div class="widget-user-image">
                        {% if book.book_img %}
                        <img style="width:100px; height: 100px;" class="img-circle elevation-2" src="{{book.author_img.url}}" alt="User Avatar">
                        {% endif %}
                      </div>
                      <div class="card-footer">
                        <div class="row">
                          <div class="col-sm-4 border-right">
                            <div class="description-block">
                              {% if book.pages %}
                              <h5 class="description-header">{{book.pages}}</h5>
                              {% else %}
                              <h5 class="description-header">50</h5>
                              {% endif %}

                              <span class="description-text">صفحة</span>
                            </div>
                            <!-- /.description-block -->
                          </div>
                              <!-- /.col -->
                          <div class="col-sm-4 border-right">
                            <div class="description-block">
                              {% if book.price %}
                                  <h5 class="description-header">${{book.price}}</h5>
                                  <span class="description-text">السعر</span>
                              {% elif book.rental_price_day %}
                                  <h5 class="description-header">${{book.rental_price_day}}</h5>
                                  <span class="description-text"> فى اليــوم </span>
                              {% endif %}

                            </div>
                            <!-- /.description-block -->
                          </div>
                              <!-- /.col -->
                          <div class="col-sm-4">
                            <div class="description-block">
                              {% if book.status == 'available' %}
                                  <h5 class="description-header text-success">{{book.status}}</h5>
                                  <span class="description-text">الحالة</span>
                              {% elif book.status == 'rental'  %}
                                  <h5 class="description-header text-warning">{{book.status}}</h5>
                                  <span class="description-text">الحالة</span>
                              {% else %}
                                <h5 class="description-header text-danger">{{book.status}}</h5>
                                <span class="description-text">الحالة</span>
                              {% endif %}

                            </div>
                            <!-- /.description-block -->
                          </div>
                              <!-- /.col -->
                        </div>
                            <!-- /.row -->
                      </div>
                      </div>
                        <!-- /.widget-user -->
                    </div>
                <!-- نهاية الكتاب -->

                {% endfor %}
             
                    <div class="row">
                      <div class="col text-center">
                        <!--اضف صورة هنا في حالة عدم وجود كتب-->
                      </div>
                    </div>
                </div>
            </div>
            <!-- Books in category -->
            
          </div>
              <!-- /.container-fluid -->
        </div>
            <!-- /.content -->
      </div>
          <!-- /.content-wrapper -->

{% endblock content %}

templates/pages/update.html
{% extends 'base.html' %}



{% block content %}

<div style="direction: rtl;" class="wrapper">

    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper">
      <!-- Content Header (Page header) -->
  <div  class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">تعديل الكتاب</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->

      {% if messages %}
      {% for msg in messages%}
        <div class="alert alert-{{msg.tags}}">
          {{msg}}
        </div>
      {% endfor %}
  {% endif %}
      <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
          
         {{form}}
        </div>
        <!-- /.card-body -->
  
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">حفظ</button>
        </div>
      </form>
    </div>
  </div>
  </div>
  

{% endblock content %}
    

  
  